plantHAT/plantHAT/app/models/plant.py
""" 
    models.plant
    ------

    Database model of the data obtained from the sensors of a plant.
"""

from extensions import db

class Plant(db.Model):
    __tablename__ = 'plant'

    id = db.Column(db.Integer, nullable=False, primary_key = True)
    name = db.Column(db.String(64), unique=True, index=True)
    temperature = db.Column(db.Float(), nullable=True)
    humidity = db.Column(db.Float(), nullable=True)
    moisture = db.Column(db.Integer(), nullable=True)
    illuminance = db.Column(db.Integer(), nullable=True)
    timestamp = db.Column(db.DateTime)

plantHAT/plantHAT/app/models/user.py
""" 
    models.user
    ------

    User model used by the app and stored in an sqlite database.
"""

from flask_login import UserMixin

from extensions import (db, bcrypt, login_manager )

class User(UserMixin, db.Model):
    """ 
    Defines the user model used by the plantHAT App 
    by using an database id, a username and a password hashed by bcrypt.
    """ 
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    profileImage = db.Column(db.String(128))

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)

    def __repr__(self):
        return '<User %r>' % self.username


    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash =  bcrypt.generate_password_hash(password).decode('utf-8')

    def verify_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

plantHAT/plantHAT/app/__init__.py
""" 
    PlantHAT - the modular plant monitoring and growth automation system based on the RaspberryPi

        This is a Raspberry Pi HAT that allows you to turn your Pi into an plant growth automation system.
        It allows you to control watering pumps, magnetic valves, sensors and light.
        It is build with the flask microframework and provides a Admin Dashboard (sb-admin v2) with charts
        that plot your sensor data to monitor plants.
        In the strategy tab you can set up growth strategies for your plants.

        TODO:
        If you connect a RaspberryPi camera you can use the Plantix API developed by PEAT (PEAT GmbH, Hannover)
        to provide you with high class, state of the art plant disease and pests detection.
        Go and check out their website at wwww.peat.ai or test their App Plantix.

        PlantHAT on GitHub: https://github.com/MrGnomes/plantHAT

        :copyright: (c) 2017 Patrick Laza.
        :license: MIT, see LICENSE for more details.
"""

from flask import Flask
from settings import config

# Import blueprints
from app import (errors, home, auth, dashboard)

# Import extensions
from extensions import (
    db,
    bcrypt,
    login_manager,
    bootstrap,
)

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

# App Factory Pattern
def create_app(config_name):
   
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    register_extensions(app)
    register_blueprints(app)
    return app

def register_extensions(app):
    
    db.init_app(app)

    # The current app is now known. Create the database
    with app.app_context():
        db.create_all()

    bootstrap.init_app(app)
    login_manager.init_app(app)
    
    return None


def register_blueprints(app):
    
    app.register_blueprint(home.views.homeBlueprint)
    app.register_blueprint(errors.views.errorsBlueprint)
    app.register_blueprint(auth.views.authBlueprint)
    app.register_blueprint(dashboard.views.dashboardBlueprint)
    return None

plantHAT/plantHAT/app/dashboard/__init__.py
from . import views

plantHAT/plantHAT/app/dashboard/views.py
""" 
    dashboard.views
    ------

    This is the admin dashboard of the plantHAT.
    It's the main view, from where on everything regarding the plant growth/watering can be monitored and controlled.
"""

from flask import (Blueprint, render_template, make_response)
from flask_login import login_required, current_user

dashboardBlueprint = Blueprint('dashboard', __name__)

@dashboardBlueprint.route("/dashboard")
@login_required
def index():
   return render_template("dashboard/index.html", username=current_user.username, profileImage=current_user.profileImage)

@dashboardBlueprint.route("/daily")
@login_required
def daily():
	return render_template("dashboard/daily.html", username=current_user.username, profileImage=current_user.profileImage)

@dashboardBlueprint.route("/monthly")
@login_required
def monthly():
	return render_template("dashboard/monthly.html", username=current_user.username, profileImage=current_user.profileImage)

@dashboardBlueprint.route("/yearly")
@login_required
def yearly():
	return render_template("dashboard/yearly.html", username=current_user.username, profileImage=current_user.profileImage)

@dashboardBlueprint.route("/strategies")
@login_required
def strategies():
	return render_template("dashboard/strategies.html", username=current_user.username, profileImage=current_user.profileImage)

plantHAT/plantHAT/app/home/__init__.py
from . import views

plantHAT/plantHAT/app/home/views.py
""" 
    home.views
    ------

    Home Screen when visiting the plantHAT server.
"""

from flask import (Blueprint, render_template)

homeBlueprint = Blueprint('home', __name__)

@homeBlueprint.route('/')
def index():
    return render_template('home/index.html')

@homeBlueprint.route("/about/")
def about():
    return render_template("home/about.html")

plantHAT/plantHAT/app/templates/dashboard/daily.html
{% extends "dashboard_base.html" %}
{% block page_title %}Dashboard - Daily{% endblock %}
{% block meta_description %} PlantHAT - A RaspberryPi based smart greenhouse{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="side-body padding-top">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Daily Overview</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $('#charts_nav').addClass('collapse in');

        $('#side_menu').find('a').each(function (i)
        {
            $(this).removeClass('active');
        });

        $('#daily_data_link').addClass("active");
    </script>
{% endblock %}

plantHAT/plantHAT/app/templates/dashboard/index.html
{% extends "dashboard_base.html" %}
{% block page_title %}Dashboard - Plantbox{% endblock %}
{% block meta_description %} Plantbox - A RaspberryPi based smart greenhouse{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="side-body padding-top">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{% endblock %}

plantHAT/plantHAT/app/templates/dashboard/monthly.html
{% extends "dashboard_base.html" %}
{% block page_title %}Dashboard - Monthly{% endblock %}
{% block meta_description %} PlantHAT - A RaspberryPi based smart greenhouse{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="side-body padding-top">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Monthly Overview</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $('#charts_nav').addClass('collapse in');

        $('#side_menu').find('a').each(function (i)
        {
            $(this).removeClass('active');
        });

        $('#monthly_data_link').addClass("active");
</script>
{% endblock %}

plantHAT/plantHAT/app/templates/dashboard/strategies.html
{% extends "dashboard_base.html" %}
{% block page_title %}Dashboard - Strategies{% endblock %}
{% block meta_description %} PlantHAT - A RaspberryPi based hydroponic smart greenhouse{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="side-body padding-top">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Strategies</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $('#strategies_nav').addClass('collapse in');

        $('#side_menu').find('a').each(function (i)
        {
            $(this).removeClass('active');
        });

        $('#strategies_link').addClass("active");
</script>
{% endblock %}

plantHAT/plantHAT/app/templates/dashboard/yearly.html
{% extends "dashboard_base.html" %}
{% block page_title %}Dashboard - Yearly{% endblock %}
{% block meta_description %} PlantHAT - A RaspberryPi based hydroponic smart greenhouse{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="side-body padding-top">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Yearly overview</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $('#charts_nav').addClass('collapse in');

        $('#side_menu').find('a').each(function (i)
        {
            $(this).removeClass('active');
        });

        $('#yearly_data_link').addClass("active");
</script>
{% endblock %}

plantHAT/plantHAT/app/templates/dashboard_base.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <title>
        {% block page_title %} PlantHAT - Dashboard {% endblock %}
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}"/>
    <meta name="keywords" content="plants, plantbox, controlled growth,raspberrypi,python,flask"/>
    <meta name="author" content="Patrick Laza"/>
	<link rel="shortcut icon" href={{ url_for('static', filename='favicon.ico') }} type="image/x-icon">

	
    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

	
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.9/css/weather-icons.min.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/animate.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/checkbox3.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/flat-admin-green.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='libs/flaticons/flaticon.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/flat_admin_style.css') }}">

	
    {% block css %}{% endblock %}

</head>

<!-- Set color theme in body class -->
<body class="flat-green">
    
    <div id="app_container"  class="app-container" style="display:none;">
		<div class="row content-container">
			<!-- Navigation -->
			{% with form=form %}
				{% include "nav.html" %}
			{% endwith %}

			{% with messages = get_flashed_messages() %}
				  {% if messages %}
					<div class="container">
						{% for message in messages %}
						 <div class="alert alert-warning">
							<button type="button" class="close" data-dismiss="alert">&times;</button>
							{{ message }}
						</div>
						{% endfor %}
					</div>
				  {% endif %}
			{% endwith %}

			{% block content %}{% endblock %}
	   </div>
    </div>

<!-- /#wrapper -->
<script type="application/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script type="application/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script type="application/javascript" src="//cdnjs.cloudflare.com/ajax/libs/metisMenu/2.2.0/metisMenu.min.js"></script>
<script type="application/javascript" src="http://code.highcharts.com/highcharts.js"></script>
<script src="{{url_for('static', filename='js/select2.full.min.js')}}"></script>
<script src="{{url_for('static', filename='js/app.js')}}"></script>

<script type="text/javascript" language="javascript">

    $(window).on('load', function () {
        if ($(window).width() > 1000) {
            document.getElementById("app_container").classList.add('expanded');
            document.getElementById('app_container').style.display = 'block';
        } else {
            document.getElementById("app_container").classList.remove('expanded');
            document.getElementById('app_container').style.display = 'block';
        }
    });

    $(window).on('resize', function () {
        if ($(window).width() > 1000) {
            document.getElementById("app_container").classList.add('expanded');
        } else {
            document.getElementById("app_container").classList.remove('expanded');
        }
    });
</script>
    
    {% block scripts %}{% endblock %}
</body>
</html>

plantHAT/plantHAT/app/templates/footer.html
    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Patrick Laza 2017</p>
        </div>
    </footer>

plantHAT/plantHAT/app/templates/home/index.html
{% extends "layout.html" %}
{% block page_title %}PlantHAT{% endblock %}
{% block meta_description %} Plantbox - A RaspberryPi based, Flask powered plant growth controller and monitor{% endblock %}
{% block content %}

      <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->

            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

        <!-- Intro Header -->
         <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <img src="{{ url_for('static', filename='img/logo_white.svg') }}" class="logo">
                        <p class="intro-text">The modular greenhouse system with real-time data of your plants.</p>
                    </div>
                </div>
                <!--<span class="plant"></span>-->
                <div class="row" align="right">
                    <a href="{{ url_for('auth.login') }}" >
						<button class="btn btn-default btn-lg">Login</button>
					</a>
                </div>
            </div>
        </div>
    </header>


    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About PlantHAT</h2>
                <p>I started this personal project to monitor the growth of my tomatoes and other vegetables and I also wanted to automate the watering based on simple strategies.</p>
                <p>Just mount the board on top of a Raspberry Pi (or connect your own boards to the GPIOs), 
                connect it to the local Internet/WLAN and use your tablet, phone or PC to check in on your plants.
                It automatically controls multiple pumps and valves based on strategies that you can set to either optimize your vegetable yield or to take care of precious plants while you are gone.</p>
                <p>Click the "Login" button, create a local account through the "Register" link and start controlling your plants growth!</p>
            </div>
        </div>
    </section>
{% endblock %}

plantHAT/plantHAT/app/templates/layout.html
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <title>
        {% block page_title %} PlantHAT {% endblock %}
    </title>
    <meta name="description" content="{% block meta_description %}{% endblock %}"/>
    <meta name="keywords" content="plants, plantbox, controlled growth,raspberrypi,python,flask"/>
    <meta name="author" content="Patrick Laza"/>
	<link rel="shortcut icon" href={{ url_for('static', filename='favicon.ico') }} type="image/x-icon">
	
    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/grayscale.css') }}">


    {% block css %}{% endblock %}

</head>

<body>

    {% block content %}{% endblock %}
<!-- /#wrapper -->

    <script type="application/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="application/javascript" src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script type="application/javascript" src="{{ url_for('static', filename='js/grayscale.js') }}"></script>
    {% block scripts %}{% endblock %}

    <div id="footer">
        {% block footer %}
        <div class="container text-center">
            <p>Copyright &copy; Patrick Laza 2017</p>
        </div>
        {% endblock %}
    </div>
</body>
</html>

plantHAT/plantHAT/app/templates/nav.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top navbar-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-expand-toggle">
                <i class="fa fa-bars icon"></i>
            </button>
            <ol class="breadcrumb navbar-breadcrumb">
                <li class="active">Dashboard</li>
            </ol>
            <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                <i class="fa fa-th icon"></i>
            </button>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <button type="button" class="navbar-right-expand-toggle pull-right visible-xs">
                <i class="fa fa-times icon"></i>
            </button>
            <li class="dropdown profile">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ username }} <span class="caret"></span></a>
                <ul class="dropdown-menu animated fadeInDown">
                    <li class="profile-img">
                        <img src="{{ profileImage }}" class="profile-img">
                    </li>
                    <li>
                        <div class="profile-info">
                            <h4 class="username">{{ username }}</h4>
                            <div class="btn-group margin-bottom-2x" role="group">
                                <button type="button" class="btn btn-default" disabled><i class="fa fa-user"></i> TODO:Profile</button>
                                <a href="{{ url_for('auth.logout') }}" class="btn btn-default"><i class="fa  fa-sign-out"></i> Logout</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>
<div class="side-menu sidebar-inverse">
    <nav class="navbar navbar-default" role="navigation">
        <div class="side-menu-container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('dashboard.index') }}">
                    <div class="icon flaticon-plant30"></div>
                    <div class="title">PlantHAT</div>
                </a>
                <button type="button" class="navbar-expand-toggle pull-right visible-xs">
                    <i class="fa fa-times icon"></i>
                </button>
            </div>

            <!-- Actual navigation sidebar -->
            <ul id="side_menu" class="nav navbar-nav" >
                
                <!-- Dashboard index -->
                <li id="dashboard_index_nav" >
                    <a href="{{ url_for('dashboard.index') }}">
                        <span class="icon fa fa-tachometer"></span><span class="title">Dashboard</span>
                    </a>
                </li>

                <!-- Charts -->

                <li class="panel panel-default dropdown">
                    <a data-toggle="collapse" href="#charts_nav">
                        <span class="icon fa fa-table"></span><span class="title">Charts</span>
                    </a>
                    <!-- Dropdown level 1 -->
                    <div id="charts_nav" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul class="nav navbar-nav">
                                <li id="daily_data_link">   <a href="{{ url_for('dashboard.daily') }}">Daily</a>   </li>
                                <li id="monthly_data_link"> <a href="{{ url_for('dashboard.monthly') }}">Monthly</a> </li>
                                <li id="yearly_data_link">  <a href="{{ url_for('dashboard.yearly') }}">Yearly</a>  </li>
                            </ul>
                        </div>
                    </div>
                </li>

                <!-- Strategies -->
                <li class="panel panel-default dropdown">
                    <a data-toggle="collapse" href="#strategies_nav">
                        <span class="icon flaticon-watering2"></span><span class="title">Control Panel</span>
                    </a>
                    <!-- Dropdown level 1 -->
                    <div id="strategies_nav" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul class="nav navbar-nav">
                                <li id="strategies_link"><a href="{{ url_for('dashboard.strategies') }}">Strategies</a> </li>
                            </ul>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
</div>